<?php

declare(strict_types=1);

namespace App\Framework\UserInterface\OpenApi\ApiProblem\ProblemDetail;

use App\Framework\UserInterface\ApiProblem\ProblemDetail\ProblemDetail;
use LogicException;
use OpenApi\Attributes as OA;

use function sprintf;

/**
 * OpenAPI shape only, reflected by swagger-php via property attributes and never instantiated.
 * The real implementation is {@see ProblemDetail}.
 */
#[OA\Schema(
    title: 'Problem Detail Response',
    description: 'A machine-readable error response, as per RFC 9457 (Problem Details for HTTP APIs).',
)]
final readonly class ProblemDetailResponse
{
    public function __construct(
        #[OA\Property(
            description: 'A URI reference that identifies the problem type.',
            example: 'https://www.rfc-editor.org/rfc/rfc9110.html#name-400-bad-request',
        )]
        public string $type,
        #[OA\Property(
            description: 'The HTTP status code generated by the origin server for this occurrence of the problem.',
            example: 400,
        )]
        public int $status,
        #[OA\Property(
            description: 'A short, human-readable summary of the problem type.',
            example: 'Validation Error',
        )]
        public string $title,
        #[OA\Property(
            description: 'A human-readable explanation specific to this occurrence of the problem.',
            example: 'The request cannot be processed due to the following errors.',
        )]
        public string $detail,
        #[OA\Property(
            description: 'A URI reference that identifies the specific occurrence of the problem.',
            example: '/api/register',
        )]
        public string $instance,
    ) {
        throw new LogicException(sprintf('%s is an OpenAPI schema only and must not be instantiated, use %s instead.', self::class, ProblemDetail::class));
    }
}
