services:
    postgres:
        image: postgres:18-alpine
        ports:
            - ${HOST_SHARED_DATABASE_PORT:-5432}:5432
        volumes:
            - postgres:/var/lib/postgresql
        environment:
            POSTGRES_USER: ${SHARED_DATABASE_USER:-user}
            POSTGRES_PASSWORD: ${SHARED_DATABASE_PASSWORD:-password}
        networks:
            - shared

networks:
    shared:
        name: shared
        external: false

volumes:
    postgres:
        driver: local
