services:
    _defaults:
        autowire: true
        autoconfigure: true

    ### Framework ###

    App\Framework\Domain\Repository\TransactionBoundary: '@App\Framework\Infrastructure\Doctrine\DbalTransactionBoundary'

    App\Framework\Infrastructure\Doctrine\DbalTransactionBoundary: ~

    _instanceof:
        App\Framework\Domain\Projection\Projector:
            tags:
                - app.projector
