services:
    _defaults:
        autowire: true
        autoconfigure: true

    ### Framework ###

    App\Framework\Domain\Repository\TransactionBoundary: '@App\Framework\Infrastructure\Doctrine\DbalTransactionBoundary'

    App\Framework\Infrastructure\Doctrine\DbalTransactionBoundary: ~

    App\Framework\Infrastructure\Symfony\Router\SymfonyInstanceProvider:
        arguments:
            $baseBackendUrl: '%env(BASE_BACKEND_URL)%'

    App\Framework\Infrastructure\Symfony\Validation\SymfonyValidator: ~

    App\Framework\UserInterface\ApiProblem\ApiProblemExceptionListener: ~

    App\Framework\UserInterface\ApiProblem\DevExceptionTransformer: ~

    App\Framework\UserInterface\ApiProblem\ExceptionTransformer: '@App\Framework\UserInterface\ApiProblem\DevExceptionTransformer'

    App\Framework\UserInterface\ApiProblem\ProblemDetail\InstanceProvider: '@App\Framework\Infrastructure\Symfony\Router\SymfonyInstanceProvider'

    App\Framework\UserInterface\Hal\HalSerializer:
        arguments:
            $baseUrl: '%env(BASE_BACKEND_URL)%'

    App\Framework\UserInterface\Validation\Validator: '@App\Framework\Infrastructure\Symfony\Validation\SymfonyValidator'

    Symfony\Component\Serializer\NameConverter\NameConverterInterface: '@serializer.name_converter.metadata_aware'

    _instanceof:
        App\Framework\Application\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        App\Framework\Application\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

        App\Framework\Domain\Model\Event\AggregateEventsSubscriber:
            tags:
                - { name: messenger.message_handler, bus: aggregate_event.bus }

        App\Framework\Domain\Projection\Projector:
            tags:
                - app.projector

        App\Framework\UserInterface\Event\DomainEventSubscriber:
            tags:
                - { name: messenger.message_handler, bus: domain_event.bus }

imports:
    - { resource: services/**/services/*.yaml }

when@prod:
    services:
        App\Framework\UserInterface\ApiProblem\ExceptionTransformer: '@App\Framework\UserInterface\ApiProblem\ProdExceptionTransformer'

        App\Framework\UserInterface\ApiProblem\ProdExceptionTransformer: ~
